# Generated by Django 5.2.6 on 2025-09-27 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_news_image_news_department_news_faculty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for the news.', null=True, upload_to='news_images/'),
        ),
    ]
