# Generated by Django 5.2.6 on 2025-10-12 22:48

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_news_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='for_all',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for the news.', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='news_images/'),
        ),
    ]
