# Generated by Django 5.2.6 on 2025-10-10 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('level', 'code'), name='uniq_course_code_per_level'),
        ),
        migrations.AddConstraint(
            model_name='level',
            constraint=models.UniqueConstraint(fields=('department', 'course_area', 'name'), name='uniq_level_per_dept_area_name'),
        ),
    ]
