# Generated by Django 5.2.6 on 2025-09-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_course_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='course_area',
        ),
        migrations.RemoveField(
            model_name='department',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='level',
            name='department',
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['course_code']},
        ),
        migrations.RenameField(
            model_name='course',
            old_name='title',
            new_name='course_title',
        ),
        migrations.RemoveField(
            model_name='course',
            name='code',
        ),
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(default=' ', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.CharField(db_index=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='lecturer_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='CourseArea',
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Level',
        ),
    ]
