# Generated by Django 5.2.6 on 2025-11-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_unique_constraints'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='course',
            name='uniq_course_code_per_level',
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.IntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('level', 'code', 'semester'), name='uniq_course_per_level_semester'),
        ),
    ]
