# Generated by Django 5.2.6 on 2026-01-15 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('faculty', 'Faculty'), ('hostel', 'Hostel'), ('admin', 'Admin'), ('landmark', 'Landmark'), ('sports', 'Sports'), ('health', 'Health'), ('religious', 'Religious'), ('commercial', 'Commercial')], default='landmark', max_length=50)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('description', models.TextField(blank=True, help_text='Optional description or directions')),
                ('is_active', models.BooleanField(default=True, help_text="Inactive locations won't show on the map")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
