# Generated by Django 5.2.6 on 2026-06-12 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_campuslocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('prompt_type', models.CharField(choices=[('STANDARD', 'Standard Announcement'), ('UPDATE', 'Actionable Update'), ('COUNTDOWN', 'Live Countdown'), ('CRITICAL', 'Critical/Non-dismissible Alert')], default='STANDARD', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('button_text', models.CharField(blank=True, max_length=50)),
                ('action_route', models.CharField(blank=True, max_length=255)),
                ('target_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Global Prompt',
                'verbose_name_plural': 'Global Prompts',
            },
        ),
    ]
