# Generated by Django 5.2.6 on 2025-12-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('level', models.IntegerField(blank=True, help_text='Academic level (100, 200, 300, 400, 500)', null=True)),
                ('semester', models.IntegerField(blank=True, help_text='Semester number (1, 2, 3)', null=True)),
                ('faculty_code', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('faculty_title', models.CharField(blank=True, max_length=255, null=True)),
                ('department_code', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('department_title', models.CharField(blank=True, max_length=255, null=True)),
                ('certificate_code', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('certificate_title', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['faculty_code', 'department_code', 'level', 'semester', 'code'],
                'indexes': [models.Index(fields=['faculty_code', 'department_code'], name='course_cour_faculty_ebb241_idx'), models.Index(fields=['level', 'semester'], name='course_cour_level_49b66a_idx')],
            },
        ),
    ]
