services:
  - type: web
    name: uniben-project
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate --noinput
    startCommand: gunicorn uniben_portal.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: uniben_portal.settings
      - key: CREATE_SUPERUSER
        value: "true"
