# Generated by Django 5.2.6 on 2026-01-05 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_alter_material_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
