# Generated by Django 5.2.6 on 2026-02-05 01:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_material_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['course_code', '-uploaded_at']},
        ),
        migrations.AddField(
            model_name='material',
            name='course_code',
            field=models.CharField(blank=True, help_text='Course code (e.g., MTH101, ENG102, CSC201)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='course_name',
            field=models.CharField(blank=True, help_text='Full course name', max_length=200, null=True),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['course_code', 'is_verified'], name='materials_m_course__448aad_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['category', 'is_verified'], name='materials_m_categor_2f6a3b_idx'),
        ),
    ]
