# Generated by Django 5.2.6 on 2026-05-21 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_campuslocation'),
        ('materials', '0005_alter_material_options_material_course_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='core.department'),
        ),
        migrations.AddField(
            model_name='material',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='core.faculty'),
        ),
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(upload_to='materials/'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['faculty', 'department'], name='materials_m_faculty_5aa6fd_idx'),
        ),
    ]
