# Generated by Django 5.2.6 on 2025-12-05 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userpreferences_usertimetableentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTodoEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=500)),
                ('time', models.CharField(blank=True, max_length=50, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Todo Entry',
                'verbose_name_plural': 'User Todo Entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
