# Generated by Django 5.2.6 on 2026-01-10 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_usertodoentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDebaterProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beginner_score', models.IntegerField(default=0)),
                ('intermediate_score', models.IntegerField(default=0)),
                ('advanced_score', models.IntegerField(default=0)),
                ('expert_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='debater_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Debater Progress',
                'verbose_name_plural': 'User Debater Progress',
            },
        ),
        migrations.CreateModel(
            name='UserGpaEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(blank=True, max_length=20)),
                ('course_name', models.CharField(max_length=255)),
                ('unit', models.FloatField()),
                ('grade', models.CharField(max_length=2)),
                ('grade_point', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpa_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User GPA Entry',
                'verbose_name_plural': 'User GPA Entries',
                'ordering': ['course_name'],
            },
        ),
        migrations.CreateModel(
            name='UserNoteEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_id', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('color', models.IntegerField()),
                ('pinned', models.BooleanField(default=False)),
                ('note_updated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Note Entry',
                'verbose_name_plural': 'User Note Entries',
                'ordering': ['-pinned', '-note_updated_at'],
                'unique_together': {('user', 'note_id')},
            },
        ),
    ]
