# Generated by Django 5.2.6 on 2026-09-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofile_network_userprofile_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='matric_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='student_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
