# Generated by Django 5.2.6 on 2026-05-28 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiassistant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAIPromptTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_room', models.CharField(max_length=50)),
                ('deep_study_messages_used', models.IntegerField(default=0)),
                ('has_active_premium_pass', models.BooleanField(default=False)),
                ('pass_expiration_datetime', models.DateTimeField(blank=True, null=True)),
                ('daily_images_uploaded', models.IntegerField(default=0)),
                ('daily_audio_memos_used', models.IntegerField(default=0)),
                ('last_interaction_date', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student AI Prompt Tracker',
                'unique_together': {('user', 'subject_room')},
            },
        ),
    ]
