# Generated by Django 5.2.6 on 2025-12-06 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('cbt_start', 'CBT Quiz Started'), ('cbt_submit', 'CBT Quiz Submitted'), ('pdf_view', 'PDF Viewed'), ('news_view', 'News Viewed'), ('event_view', 'Event Viewed'), ('timetable_view', 'Timetable Viewed'), ('map_view', 'Map Viewed'), ('ai_chat', 'AI Chat Used')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action', 'timestamp'], name='app_analyti_action_c68d45_idx'), models.Index(fields=['user', 'timestamp'], name='app_analyti_user_id_431f8c_idx')],
            },
        ),
    ]
