# Generated by Django 5.2.6 on 2026-02-28 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('cbt_start', 'CBT Quiz Started'), ('cbt_submit', 'CBT Quiz Submitted'), ('pdf_view', 'PDF Viewed'), ('news_view', 'News Viewed'), ('event_view', 'Event Viewed'), ('timetable_view', 'Timetable Viewed'), ('map_view', 'Map Viewed'), ('ai_chat', 'AI Chat Used'), ('course_view', 'Course Viewed'), ('search_not_found', 'Search Not Found')], max_length=50),
        ),
    ]
