# Generated by Django 5.2.6 on 2026-01-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebaterQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField(help_text='The true/false statement')),
                ('answer', models.BooleanField(help_text='True if statement is correct, False if incorrect')),
                ('category', models.CharField(choices=[('General Knowledge', 'General Knowledge'), ('Science', 'Science'), ('Uniben History', 'Uniben History')], default='General Knowledge', max_length=50)),
                ('difficulty', models.CharField(blank=True, help_text='Optional difficulty tag', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text="Inactive questions won't appear in game")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', '-created_at'],
            },
        ),
    ]
